* Feed Forward propogation - humne input diya, it passes through a hidden layer and gives us the ouput
* Back propogation - if desired output nahi aya toh model backwards run kare ga and will adjust weights to achieve the desired output. During this process model learns how to balance and set weights.This thing goes on (forward and backwards) until we achieve the desired result.
* cost function/error  = actual value(jo desired thi) - predicted value(jo model ne predict ki)\


# Neural Network Architecture.

### single layer perceptron model (SLP)
* perceptron is fundamental unit
* neural network has only input and output layer. no hidden layers.

### Radial Basis Network (RBN)

* composed of input, single hidden and then output layer
* there are feed forward neural networks which only uses RBN as activation function
* ACTIVATION FUNCTION - decides whether neuron should be activated or not.
* in RBN , a RBF (Radial basis Function) is the activation function. It assigns a real value to each i/p and also the value produced by the RBF is always an absolute value.

### Multi-layer Perceptron (MLP)
* more than one hidden layer of neurons.
* input , output and many hidden layers in between
* also known as deep feed forward NN
* hidden layers are the real computational engine of MLP NN 

### Recurrent Neural Network (RNN)
* process memory 
* value of hidden layer neuron is a combination of data it recieves from lower layer and it's PREVIOUS VALUE.
* previous value contributes to the current value and this feature is what enables the NN to process memory
* RNN are neural networks that may be used to analyze time series data or data that involves sequences .
* an ordinary feed forward NN you need to have a large number of independent data points, however if data is arranged in a way that each data point is dependent on the one before it, we will have to make changes to the NN to account for these interdependencies
* the memory lets RNN's keep the track of prior input so they may create next new output in sequence

#### Long Short-Term Memory (LSTM) RNN
* is memory cell in incorporated in the hidden cell neurons, is called LSTM network. 
* LSTM is a type of RNN
* LSTM is able to learn long term dependencies by the use of short term memory network.
* by design, these do not suffer from the long term dependency issue. they don'r need to work hard on how to retain knowledge for lengthy periods of time.

#### Hopfield Neural Network
* special type of RNN.
* different from other NN.
* no. of neurons is the same as the number of inputs and outputs
* we then have the same number of inputs and outputs. 
* Hopfield NN is a fully interconnected network of neurons in which each neuron is connected to every other neuron.
* Network is trained with input patterns by setting a value of neurons equal to the value of the desired pattern.
* then the weights are computed through deep learning algorithms.

#### Boltzman Machine Neural Network
 * similar to hopfield except, some neurons are directly connectly to inputs while others are not associated to inputs directly.
 * weights are initialized randomly and learned through back propogation algorithm.
 * also a type of RNN
 * Composed of nodes that make binary judgments and are predisposed to particular biases
* ** In this context, "binary judgments" means that each node can only choose between two options, often represented as "yes" or "no," "true" or "false," or "1" or "0." The "predisposed to particular biases" aspect indicates that these nodes have inherent inclinations or preferences that influence their decision-making process, leading them to make certain choices more frequently or readily than others. The presence of biases can have significant implications on the outcomes and behavior of the overall system. Addressing biases is an essential concern in designing fair and ethical AI systems. **

# Activation Functions
* helps neural network to learn complex patterns in the data.
* activation function takes input from the output signal of previous neurons and them into some form that can be taken as input to the next neuron.
* it takes some input and apply some function on that input to get a result and this result is transferred to next neurin.
* activation function is also known as transfer function
###### LINEAR ACTIVATION FUNCTION vs NON LINEAR ACTIVATION FUNCTIONS
* NN with no activation function is linear in nature like polynomial of one degree or as a linear regression model.
* linear functions have less power to learn complex functional mapping from data
* one of the main purposes of activation function is to introduce non linearity to the output of a neuron bcz real world problems are non linear, high dimensional and complicated. 
* non linear activation function helps to mimic the real world accurately
IMPORTANT TEMINNOLOGIES FOR NON LINEAR ACTIVATION FUNCTION
* Differential Function - Change in y-axis w.r.t. change in X-axis(slope)
* Monotonic Function - A function which is increasing on its entire domain or decreasing on its entire domain
### Non Linear Activation Functions

#### 1 -The Sigmoid Function
*  range is limited to greater than 0 and less than 1. (0<range<1).
* as range is zero to one, it is specially used for models where we have to predict probability as the output
* its diffrentiable which means we can find slope between any two points/
* it is monotonic function
* it is not very useful in real world examples because of the following 3 reasons:
* 1 - its computational inexpensive
* 2- It is not zero centered which means the range only consists of either positive or negative values.
* 3- It causes vanishing gradient problems: this problem is encountered when an Artificial Neural Network is trained with gradient based learning methods and back propogation. In such methods each of the NN which recieves an update proportional to its partial derivative of the error function with respect to the current weight in each iteration of training
* ** in worst case the gradient value will be so small that it might not be able to change any weight.

A sigmoid function will always output a value between 0 and 1 regardless of any real number input. Basically, Any real number input will be converted to a number between 0 and 1. hence, sigmoid function is said to squeeze values.

#### 2- Hyperbolic Tangent Function
* better version of sigmoid function bcz it ranges from -1 to 1.
* it is also a differentiable function and a monotonic function.
* There are applications where the hyperbolic tangent function is advantageous since it falls below zero
* e.g. negative inputs are much strongly negative and zero inputs are mopped near zero in the hyperbolic tangent graph
![](HyperbolicTangentGraph.png)
* this is an advantage because it maps the -ve inputs extremely negative. 
* Hyperbolic Tangent Funtion is mainly used for classification between 2 classes
* Hyperbolic Tangent Funtion is used in feed forward propogation in order to increase difference between outputs.n 

#### 3- Softmax Function
* this particular activation function works in the output layer
* it applies a standard exponential function to all the values in the output layer. then it does the normalization by dividing each value by the sum of all exponentials. so this way all values sum up to 1
* computes the probability or confidence score for each attribute,so it is used in multiclass classification problems
* it is also a differentiable function

#### 4- Recified Linear Unit (ReLU) function 
* if the value is less than 0, the function becomes zero
* if value is equal to zero or greater than zero, the function becomes the number.
* commonly used in Convolutional Neural Networks, as well as in deep learning approached bcz it doesn't cause vanishing gradient problems
* it is also differentiable function
* not a monotonic function
* range of this activation function is zero to infinity.
* One problem with this function is that we lose data that is less than zero and our NN learns nothing from those neurons.
* moreover, it maps all the values lesser than zero to zero
* not proper appraoch bcz it makes our Neural Network unstable

#### 5- Leaky Recified Linear Unit (ReLU) function 
* modification of the ReLU function, it solves the negative impact of of the ReLU function.
* Usually the value for 'a' in diagram is around 0.01.
![](LeakyReLU.png)
* range of Leaky ReLU is from negative infinity to positive infintiy
* differentiable and a monotonic function



## Gradient Decent
How network adjust its weights and learn by Itself?

* most popular optimization algorithm in ML and DL
* it finds the values of a function's parameters, coefficients that minimize the cost function as far as possible.
* You start by defining the initial parameter values and from there gradient decent uses calculus to iteratevly adjust he values so that they minimize the given cost function
![](GradientDecent.png)
* assume this graph is cost function of our model. Blue dots are different iterations where different weight adjusted on each iteration.
* we will get a different cost function on each point because it is changing weights after each iteration. 
* It takes initial value of the function and applies the formula shown:
![](GDFormula.png)
* here f(a)= laplace operator function of 'a'.
* from current position we either move forward or backward, and the size of our step is instructed by the gamma laplace of the function of a.
* we can also assume that the size of the step is defined by the value of the gradient or slope.
* high gradient = larger step size
*after some steps we will be able to reach the minimum value of  cost function.

## Stochastic Gradient Decent (SGD)
* main drawback of gradient decent is that it is limited to a convex function in terms of shape of teh function.
* for a non convex shape as shown, gradient decent wont produce the desired results bcz we have multiple minimal values, lcal minimal values and in this case, gradient decent might not find the optimal minima (Global Minimum) from the shape.
* for this kind of situation we opt for the STOCHASTIC GRADIENT DECENT OPTIMIZATION TECHNQUE
![](StochasticDecent.png)

* as name stichastic represents, this technique has some randomness
* in SGD technique. we find out the gradient of the cost function of a single input at each iteration instead of the sum of the gradient of the cost function of all inputs
* with SGD technique, since only one sample from the dataset is chosen at random for each iteration, the path taken by the algorithm to reach the minima is usually noisier than typical gradient decent algorithm
* path taken by the algorithm does not matter as long as we reach the minimaand with a significantly shorter training time.
* typically SGD takes a random single value at a time

if algorithm takes a subset of values rather than a single value, in this case, it is known as mini batch gradient decent

* One imporant difference between GD and SGD is that in gradient decent for every iteration, we take the whole dataset to measure the gradient and obtain parameters of the cost function. While in SGD we take a single value or a subset of values in iteration to measure gradient and then to update the parameters of cost function.
* so if the data is very large, gradient decent may take too long. In this case SGD would be the faster
![](SGD2.png)

 # How ANN works?
    
    * diference un ML and DL is the presence of hidden layer in DL
   
   * ![](ANN.png)
   * in this example the activation function is sigmoid
   
 ### advantages of ANN 
 * have the ability to worl with incomplete knowledge. After the ANN is trained, the data may produce output even with incomplete information. Loss of performance here depends on the importance of missing information.
 * Fault Tolerance - corruption of one or more cells of the ANN will not stop the generation of output
 * parallel performance capability - the ANN can perform more than one job at a time
 
 ### disadvantges of the ANN
 * hardware dependency - ANN require processors with parallel processing power in accordance with their structure. for this reason the realization of equipment is dependent.
 * Determination of proper network structure -  There is no specific rule for determining the structure of ANN. Appropriate network structure is achieved through experience as well as through trial and error.
 
 # applications of ANN
 * handwritten recognition
 * image compression
 * stock exchange prediction

# Using ANN for classification


# problem statement - To see if customers leave the bank or stay.
* creating a predictive model to predict behaviour of new customers, whether he or she will stay in the bank or leave the bank so that the bank can offer something special for the customer, about whom our model predicted, will leave the bank 

In [1]:
# data preprocessing 
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
 data = pd.read_csv('Churn_Modelling.csv')

In [4]:
data

RowNumber  CustomerId    Surname  CreditScore Geography  Gender  Age  \
0             1    15634602   Hargrave          619    France  Female   42   
1             2    15647311       Hill          608     Spain  Female   41   
2             3    15619304       Onio          502    France  Female   42   
3             4    15701354       Boni          699    France  Female   39   
4             5    15737888   Mitchell          850     Spain  Female   43   
...         ...         ...        ...          ...       ...     ...  ...   
9995       9996    15606229   Obijiaku          771    France    Male   39   
9996       9997    15569892  Johnstone          516    France    Male   35   
9997       9998    15584532        Liu          709    France  Female   36   
9998       9999    15682355  Sabbatini          772   Germany    Male   42   
9999      10000    15628319     Walker          792    France  Female   28   

      Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0          2       0.00              1          1               1   
1          1   83807.86              1          0               1   
2          8  159660.80              3          1               0   
3          1       0.00              2          0               0   
4          2  125510.82              1          1               1   
...      ...        ...            ...        ...             ...   
9995       5       0.00              2          1               0   
9996      10   57369.61              1          1               1   
9997       7       0.00              1          0               1   
9998       3   75075.31              2          1               0   
9999       4  130142.79              1          1               0   

      EstimatedSalary  Exited  
0           101348.88       1  
1           112542.58       0  
2           113931.57       1  
3            93826.63       0  
4            79084.10       0  
...               ...     ...  
9995         96270.64       0  
9996        101699.77       0  
9997         42085.58       1  
9998         92888.52       1  
9999         38190.78       0  

[10000 rows x 14 columns]

In [5]:
# x - independent variables
# y- dependent variables

In [7]:
x = data.iloc[:,3:13].values
y = data.iloc[:,13].values

In [8]:
x

array([[619, 'France', 'Female', ..., 1, 1, 101348.88],
       [608, 'Spain', 'Female', ..., 0, 1, 112542.58],
       [502, 'France', 'Female', ..., 1, 0, 113931.57],
       ...,
       [709, 'France', 'Female', ..., 0, 1, 42085.58],
       [772, 'Germany', 'Male', ..., 1, 0, 92888.52],
       [792, 'France', 'Female', ..., 1, 0, 38190.78]], dtype=object)

In [9]:
y

array([1, 0, 1, ..., 1, 1, 0], dtype=int64)

In [10]:
# label encoding
# transforming object values to numeric values
# geography - hot encoding using sklearn

from sklearn.preprocessing import LabelEncoder, OneHotEncoder
labelencoder_x_2  = LabelEncoder()
x[:,2] = labelencoder_x_2.fit_transform(x[:,2])
#fit_transform - maps string values to numerical values


In [13]:
pd.DataFrame(x)

0        1  2   3   4          5  6  7  8          9
0     619   France  0  42   2        0.0  1  1  1  101348.88
1     608    Spain  0  41   1   83807.86  1  0  1  112542.58
2     502   France  0  42   8   159660.8  3  1  0  113931.57
3     699   France  0  39   1        0.0  2  0  0   93826.63
4     850    Spain  0  43   2  125510.82  1  1  1    79084.1
...   ...      ... ..  ..  ..        ... .. .. ..        ...
9995  771   France  1  39   5        0.0  2  1  0   96270.64
9996  516   France  1  35  10   57369.61  1  1  1  101699.77
9997  709   France  0  36   7        0.0  1  0  1   42085.58
9998  772  Germany  1  42   3   75075.31  2  1  0   92888.52
9999  792   France  0  28   4  130142.79  1  1  0   38190.78

[10000 rows x 10 columns]

In [14]:
from sklearn.compose import ColumnTransformer

In [19]:
ct = ColumnTransformer([('ohe',OneHotEncoder(),[1])], remainder = 'passthrough')


*  first augment in square is an array called transformers, which is a list of tuples. the array has the collowing element in the same order: 
1) A name for the column transformer i.e. 'ohe' in this case which will make setting of parameters and searching of trandformers easy
2) Transformer : Here we are supposed to provide an estimator. we can also just passthrogh or drop if we want, but since we are encoding the data in this example we will use OneHotEncoder() here. Remember the estimator you use here needs to support fit and transform
3) list of columns that you want to be transformed. in this case the 2nd column i.e. [1].

* the second parameter we are interested in is the remainder this will tell the trandformer what to do with the other columns in tha dataset. By default, only the columns that are transformed will be returned by the transformer. all other columns will be dropped. But we have the option to tell the transformer what to do with the other columns: we can either drop them, pass them through unchanged or specify another estimator if you want to do some more processing, in this example we made sure all the remainder columns are allowed to pass through without any changes


In [20]:
x = np.array(ct.fit_transform(x), dtype = np.str)

# takes all values from transformed dataset and convert it to an array. this array consit of the list of each row and and all of the values are converted to string using dtype = np.str augment.

C:\Users\Danish\AppData\Local\Temp\ipykernel_26936\3306601298.py:1: DeprecationWarning: `np.str` is a deprecated alias for the builtin `str`. To silence this warning, use `str` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.str_` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  x = np.array(ct.fit_transform(x), dtype = np.str)


In [21]:
x=x[:,1:]

# we are ignoring the first index bcz the same information can be achieved from index 1 and 2 that is colum 0 and 1 in the x printed below.
# column number 0 and 1 ka combination apko bata raha hai k konsi country hai or dataframe x jo phele print kia tha uska column 1 bh same information de rha tha. isiliye humne usko hata k encoded wale columns rehne diye
#we managed to reduce one input neuron without the loss of any information 

In [30]:
pd.DataFrame(x)

# first 2 columns together are hot encoded for geography. e.g 0 0 means france, 0 1 means spain and 1 0 means germany 

0    1    2  3   4   5          6  7  8  9          10
0     0.0  0.0  619  0  42   2        0.0  1  1  1  101348.88
1     0.0  1.0  608  0  41   1   83807.86  1  0  1  112542.58
2     0.0  0.0  502  0  42   8   159660.8  3  1  0  113931.57
3     0.0  0.0  699  0  39   1        0.0  2  0  0   93826.63
4     0.0  1.0  850  0  43   2  125510.82  1  1  1    79084.1
...   ...  ...  ... ..  ..  ..        ... .. .. ..        ...
9995  0.0  0.0  771  1  39   5        0.0  2  1  0   96270.64
9996  0.0  0.0  516  1  35  10   57369.61  1  1  1  101699.77
9997  0.0  0.0  709  0  36   7        0.0  1  0  1   42085.58
9998  1.0  0.0  772  1  42   3   75075.31  2  1  0   92888.52
9999  0.0  0.0  792  0  28   4  130142.79  1  1  0   38190.78

[10000 rows x 11 columns]

In [32]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size = 0.2, random_state = 0)

# random state = 0 tells pur method not to randomly chose rows so that the corresponsing values in all the variables match the same row and if this code is run again, it should choose the same rows as the first time

In [33]:
# FEATURE SCALING
# technique used to standarize the independent feature present in the data in a fixed range
# e.g. in out data some ranges are 0 to 1, some are 0 to 100, some are 0 to 100000. These huge ranges reqire a lot of time for calculation
#to vercome this problem we perform feature scaling

from sklearn.preprocessing import StandardScaler

In [34]:
sc = StandardScaler()

In [36]:
x_train = sc.fit_transform(x_train)
x_test = sc.transform(x_test)

# here we used fit_transform on training set bcz we learn the parameters of scaling on the training data and at the same time we scale the training data
# now for the test set we only use transform bcz we want to use the scaling parameters learnt on the training set. there is no need for fir_transform


In [39]:
pd.DataFrame(x_train)

0         1         2         3         4         5         6   \
0    -0.569844  1.743090  0.169582 -1.091687 -0.464608  0.006661 -1.215717   
1     1.754865 -0.573694 -2.304559  0.916013  0.301026 -1.377440 -0.006312   
2    -0.569844 -0.573694 -1.191196 -1.091687 -0.943129 -1.031415  0.579935   
3    -0.569844  1.743090  0.035566  0.916013  0.109617  0.006661  0.473128   
4    -0.569844  1.743090  2.056114 -1.091687  1.736588  1.044737  0.810193   
...        ...       ...       ...       ...       ...       ...       ...   
7995  1.754865 -0.573694 -0.582970 -1.091687 -0.656016 -0.339364  0.703104   
7996 -0.569844  1.743090  1.478815 -1.091687 -1.613058 -0.339364  0.613060   
7997 -0.569844 -0.573694  0.901515  0.916013 -0.368904  0.006661  1.361474   
7998 -0.569844  1.743090 -0.624205 -1.091687 -0.081791  1.390762 -1.215717   
7999  1.754865 -0.573694 -0.284011 -1.091687  0.875251 -1.377440  0.511364   

            7         8         9         10  
0     0.809503  0.642595 -1.032270  1.106432  
1    -0.921591  0.642595  0.968738 -0.748664  
2    -0.921591  0.642595 -1.032270  1.485335  
3    -0.921591  0.642595 -1.032270  1.276528  
4     0.809503  0.642595  0.968738  0.558378  
...        ...       ...       ...       ...  
7995  0.809503  0.642595  0.968738  1.091330  
7996 -0.921591  0.642595  0.968738  0.131760  
7997  0.809503  0.642595 -1.032270  1.412320  
7998  0.809503  0.642595  0.968738  0.844321  
7999 -0.921591  0.642595 -1.032270  0.324725  

[8000 rows x 11 columns]

In [40]:
# building ANN
from tensorflow.keras.models import Sequential
from keras.models import Sequential
from keras.layers import Dense

# importing sequential class bcz it allows us to build an ANN but as a sequence of layers
# ANN are built with fully connected layers. in order to implement the ANN,we need to initizalize the network

In [41]:
#we start by creating object of our sequential class
classifier = Sequential()

In [42]:
# Adding the input layer and the first hidden layer
classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'relu', input_dim = 11))


* This is going to add a further component of networks to our model
* in the above code, add method takes input from the dense class. Here dense creates a fully connected 2 layer network. This is composed of 11 input neurons and 6 output neurons.
* we will add more layers like this so that the six output neurons will be the hidden layer of out complete network.
* the parameters for dense include: 
* 1) units (represents the number of last layer neurons for now), 
* 2) kernel_intializer (the neural network needs to start with some weights and then iteratively update them to better values). The term kernel_intializeris fancy term for which a statistial districution or a function is used to initialize the weights. In case of a statistical distribution, the library will generate numbers from the statistical distribution and use them as starting weights. In our code the value for this parameter is uniform. this means that all weights will be uniformly distributed in our network at first
* 3) activation - this refers to the activation function, we gave used the rectifier function RELU.
* 4) input_dim - dimensions of input neurons, in out case it is 11 bcz we have 11 independent variables (inclusing 2 columns of geography)


In [43]:
# adding next hidden layer
classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'relu'))



*  same code as previous one, we just dont need the input_dim parameter because it automatically connects to the previous layer of our network. 
* so 6 neurons from the previous layer will be input to this layer.
* until now we have one input layer and 2 hidden layers


In [45]:
# adding the output layer
classifier.add(Dense(units = 1, kernel_initializer = 'uniform', activation = 'sigmoid'))


* in output layer we need just one neuron bcz as you can see in the dataset we have dependent variable in binary form (0 -customer stay or 1- customer leave)
* unit parameter is 1 and actication function is sigmoid (bcz sigmoid activation function provides the probability of a customer staying in the bank or leaving)

In [49]:
# compiling the ANN
# we need to train and tune the ANN according to our data

classifier.compile(optimizer = 'adam', loss = 'binary_crossentropy',metrics = ['accuracy'])

*  compile is a method of the Tensor Flow library while compiles the ANN together.
* first parameter is the optimizer. its value in our code is adam. this perform the stochastic gradient decent optimizer technique .
* next is the loss parameter, which represents the loss function. It is an optimization function which is used in case of training a classification model which classifies the data by predicting the probability of whether the data belongs to one class or the other.
* one thing we need to be aware of while doing a binary prediction similar to this one, always use the loss function as 'binary_crossentropy' . the binary_crossentropy function computes the cross entropy loss between the true and predicted levels.
* third parameter is about evaluation of our network. To evualte our ANN we have used the accuracy metrics. Accuracy metrics calculates how often prediction equal labels. This matrix create 2 local variables: total and count that are used to compute the frequency with which y_pred matches y_true


In [50]:
#fitting the ANN model to the training set
classifier.fit(x_train,y_train,batch_size = 10, epochs  = 100)



Epoch 1/100
800/800 [==============================] - 2s 2ms/step - loss: 0.4854 - accuracy: 0.7960
Epoch 2/100
800/800 [==============================] - 1s 1ms/step - loss: 0.4277 - accuracy: 0.7960
Epoch 3/100
800/800 [==============================] - 1s 2ms/step - loss: 0.4212 - accuracy: 0.8008
Epoch 4/100
800/800 [==============================] - 1s 1ms/step - loss: 0.4178 - accuracy: 0.8231
Epoch 5/100
800/800 [==============================] - 1s 2ms/step - loss: 0.4155 - accuracy: 0.8270
Epoch 6/100
800/800 [==============================] - 1s 1ms/step - loss: 0.4138 - accuracy: 0.8291
Epoch 7/100
800/800 [==============================] - 1s 2ms/step - loss: 0.4128 - accuracy: 0.8319
Epoch 8/100
800/800 [==============================] - 1s 2ms/step - loss: 0.4118 - accuracy: 0.8328
Epoch 9/100
800/800 [==============================] - 1s 2ms/step - loss: 0.4102 - accuracy: 0.8326
Epoch 10/100
800/800 [==============================] - 1s 1ms/step - loss: 0.4097 - accura

800/800 [==============================] - 2s 2ms/step - loss: 0.4010 - accuracy: 0.8353
Epoch 82/100
800/800 [==============================] - 1s 2ms/step - loss: 0.3998 - accuracy: 0.8353
Epoch 83/100
800/800 [==============================] - 1s 2ms/step - loss: 0.4006 - accuracy: 0.8356
Epoch 84/100
800/800 [==============================] - 2s 2ms/step - loss: 0.4004 - accuracy: 0.8351
Epoch 85/100
800/800 [==============================] - 1s 2ms/step - loss: 0.4008 - accuracy: 0.8342
Epoch 86/100
800/800 [==============================] - 1s 2ms/step - loss: 0.4003 - accuracy: 0.8354
Epoch 87/100
800/800 [==============================] - 1s 2ms/step - loss: 0.4002 - accuracy: 0.8351
Epoch 88/100
800/800 [==============================] - 1s 2ms/step - loss: 0.4008 - accuracy: 0.8355
Epoch 89/100
800/800 [==============================] - 1s 2ms/step - loss: 0.4006 - accuracy: 0.8355
Epoch 90/100
800/800 [==============================] - 2s 2ms/step - loss: 0.4002 - accuracy: 

* 1st we have values for input neurons, then we have values for output layer neurons
* 3rd augment is the batch_size- instead of comparing out results with real results one by one, its better to perform this task in a batch, so out code takes 10 rows at a time
* last augment is epochs, epochs is the number of times an algorithm visits the dataset. In other words, epoch is one backward and one forward pass of all the training examples.
* the neural network has to train on a certain number of epochs to improve the accuracy over time
* we can see accuracy of each epochs improving over time

In [51]:
# predicting the test set results
y_pred = classifier.predict(x_test)
y_pred = (y_pred>0.5)

63/63 [==============================] - 0s 1ms/step


* we are defining that if y_pred is in between 0 and 0.5 then this new y_pred will become 0 i.e. false.
* is y_pred is larger than 0.5 then the new y_pred will become 1 i.e. True

In [57]:
y_pred

array([[False],
       [False],
       [False],
       ...,
       [False],
       [False],
       [False]])

In [58]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test,y_pred)

In [61]:
print(cm)

[[1595    0]
 [ 405    0]]


* a confusion matrix is also called as an error matrix. it is summary of prediction results on a classification problem.
* e.g.
* [[1499 96]
* [189 216]]

* 1499 true values are correctly predicted true
* 96 false values are incorrectly predicted true.
* 189 true values are incorrectly predicted False.
* 216 false values are correctly predicted false.
 

In [62]:
accuracy_score(y_test,y_pred)

0.7975

# Convolutional Neural Networks (ConvNet)
* very important part of many computer vision applications
* It is a class of neural networks most commonly applied to analyze images.
* nomrally when we think of nn we think about matrix multiplication but that is not the case with CNN.
* it uses a special technique called convolution. it is a mathematical operation on two functions. when two function e.g. F and G are combined mathematically, the result is a third function that expresses that how the shape of one is modified by the shape of other.
* in mathematics and especially functional , convolution is a matematical function on 2 functions F and G that results in a third function that expresses how the shape of one is modified by the shape of the other.
* the word convolution refers to both of the outcome function and the technique of calculating it and it is used inter changeably.
*  after one function is reversed and shifted, the convolution is defined as the integral of the product of the two functions after they've been combined together . The integral is calculated for all possible values of shift resulting in the convolution function being produced
* In a CNN, our input image can be either grid scale or colorful
* image is made of pixels range from 0 to 255. we need to normalize them i.e. convert the range between 0 and 1 before passing it to the model.
### Components of a CNN in detail
* works in 2 steps i.e. Feature Extraction and Classification
![](CNN1.png)

#### Convolution layer

* convolution layer is the layer where the filter is applied to our input image to extract or detect its features. 
* A filter is applied to image multiple times and creates a feature map which helps in classifying the input image
* 6 by 6 ki image pey 3 by 3 ka filter lagaya. result is a feature map of 4 by 4 that is  which has some ingormation about the input image
![](ConvLayer.png)
* in real life many filters are applied to image to extract information
* as in the figure, filter is applied to the green highlighted part of the image.
* pixel values of the image are multiplied by the values of filter and then summed up to get the final value. 
* in nest step the filter is shifted by one column. This jump to the next column or row is called as Stride.
* stride of 1 means we are shifting by one column
* once we get the feature map, an activation function is applied to it to introduce non linearity
* activation funtion ina neural network defines how the weighted sum of the inputs is transformed into a output from a node or nodes in layer of the network.
* Feature map that we get here is smaller than the size of our image when the center of our filter sits on a value to change other the values of the filter must also sit on some values. in our case the center of the filter cannot sit on the outermost values of our image. So, we have lost a layer from each side.
* if our filter is  5 by 5 then we lose two outer most layers from all sides.
* as we increase the value of stride, the size of the features map decreases.

### Pooling layer
![](PoolingLayer.png)


* here in this image we are doing max pooling of 2 by 2 with a stride of 2. 
* pooling is a method to convert an input image to a lower resolution version, which still contains the large or important elements of the input image
* the most common pooling types are max pooling and average pooling
* maxpooling extracts the maximum value of the area it convolves.
* average pooling computes thea average of the value of the area it convolves. 
* Average pooling method smooths out the image and hence the sharp features may not be identified when this poooling method is used
* Max pooling selects the brighter pixels from the image. It is useful when the background of the image is dark and we are interested in only the lighter pixels of the image



### Fully Connected layer
* until now we have performed all the feature extraction steps
* convolution + pooling combinely extract different features from an image 
* for example, the edges of a shape in an image can be detected. If image is of a face, then eyes, nose and mouth can be detected.
* After convolution + pooling layers we add a couple of fully connected layers to wrap up the CNN architecture
* this is the same fully connected ANN architecture that we had previously in ANN
![](CNNarch.png)
* the output of both Convolution and the pooling layers are 2 dimensional, but a fully connected layer expects a 1 D vectors of numbers. So we flatten the output of final pooling layer to a vector, and that becomes the input to the fully connected layer.
* Flattening - arranging 2D numbers into a 1D vector.
* These Fully connected layers connect the information extracted from the previous steps i.e. convolution layers and the pooling layers to the output layer and eventually classifies the input image into the desired label

# IMPLEMENTATION

### MNIST Handwritten Digit Data
* all images have the same square size i.e. 28 x 28 pixels
* image are gray scale
* all are handwritten digits

In [63]:
# imporing libraries

from tensorflow.keras.datasets import mnist
from tensorflow.keras.models import Sequential # model type (Sequential is the easiest way to build a model in keras. Allows u to build model layer by layer)
from tensorflow.keras.layers import Conv2D # becz we are dealing with 2D images.2 dimensional convolution to help us in Convolution layers
from tensorflow.keras.layers import MaxPool2D
from tensorflow.keras.layers import Flatten
from tensorflow.keras.layers import Dropout
from tensorflow.keras.layers import Dense


#### building the CNN model


In [64]:
# here we are loading the data
(x_train,y_train),(x_test,y_test) = mnist.load_data()

11490434/11490434 [==============================] - 6s 1us/step


* resize all images to specific size and color.
* although in this example all images are grayscale and of same size i.e. 28 by 28 pixels
* in real life it is not the case, color and size of images are different
* we do so by the reshape method which take 4 augments
* 1st augment is for the number of images
* 2nd is the number of pixels in column of image
* 2rd is the number of pixels in the row.
* 4th is the augment that represents the color 


In [65]:
# reshaping the data
x_train = x_train.reshape((x_train.shape[0]),x_train.shape[1],x_train.shape[2],1)

In [66]:
x_test = x_test.reshape((x_test.shape[0]),x_test.shape[1],x_test.shape[2],1)


The line of code you provided is reshaping a 4-dimensional array `x_test` to add an additional dimension of size 1. This operation is typically done when working with Convolutional Neural Networks (CNNs) for image processing tasks.

Let's break down the code step by step:

1. `x_test` is the input data for testing. It is assumed to be a 4-dimensional array, where the dimensions represent the following:
   - Dimension 1: Number of samples in the test data (the batch size).
   - Dimension 2: Height of each sample image.
   - Dimension 3: Width of each sample image.
   - Dimension 4: Number of channels in each sample image. For grayscale images, this is 1; for RGB images, this is 3 (R, G, and B channels).

2. `x_test.shape` returns a tuple representing the shape of the `x_test` array. For example, if `x_test` has a shape of (1000, 28, 28, 3), it means there are 1000 images in the test set, each having a size of 28x28 pixels, and each image has 3 channels (RGB).

3. `x_test.shape[0]` refers to the first dimension of the `x_test` array, which is the number of samples in the test data (batch size). Similarly, `x_test.shape[1]` and `x_test.shape[2]` refer to the height and width of each sample image, respectively.

4. `x_test.reshape((x_test.shape[0]), x_test.shape[1], x_test.shape[2], 1)` reshapes the `x_test` array by adding an extra dimension at the end with size 1. This effectively converts the array into a 4-dimensional array with the same number of samples, height, and width, but now each sample image has only one channel.

The reason for adding this extra dimension is that many CNN architectures expect input data with four dimensions, including a single channel for grayscale images or three channels for RGB images. The additional dimension allows the CNN to process the data correctly and apply convolution operations across the image.



In [67]:
# here we are checking the shape after reshaping
print(x_train.shape)
print(x_test.shape)

# out of 70000 images, 60000 are given for training and 10000 for testing

(60000, 28, 28, 1)
(10000, 28, 28, 1)


In [68]:
# here we are normalizing the pixel values
x_train = x_train/255
x_test = x_test/255

* we know that the pixel values in for each image in the dataset are unsigned integers in the  range of black and white (0 -255).
* some scaling is required so a good start is to normalize the pixel values of grayscale images .e.g rescaling them to the range 0 to 1.
* this involves first converting the data type from unsigned integers to floats then dividing the pixel values by the max value 255

In [69]:
print(x_train)
print(x_test)

[[[[0.]
   [0.]
   [0.]
   ...
   [0.]
   [0.]
   [0.]]

  [[0.]
   [0.]
   [0.]
   ...
   [0.]
   [0.]
   [0.]]

  [[0.]
   [0.]
   [0.]
   ...
   [0.]
   [0.]
   [0.]]

  ...

  [[0.]
   [0.]
   [0.]
   ...
   [0.]
   [0.]
   [0.]]

  [[0.]
   [0.]
   [0.]
   ...
   [0.]
   [0.]
   [0.]]

  [[0.]
   [0.]
   [0.]
   ...
   [0.]
   [0.]
   [0.]]]


 [[[0.]
   [0.]
   [0.]
   ...
   [0.]
   [0.]
   [0.]]

  [[0.]
   [0.]
   [0.]
   ...
   [0.]
   [0.]
   [0.]]

  [[0.]
   [0.]
   [0.]
   ...
   [0.]
   [0.]
   [0.]]

  ...

  [[0.]
   [0.]
   [0.]
   ...
   [0.]
   [0.]
   [0.]]

  [[0.]
   [0.]
   [0.]
   ...
   [0.]
   [0.]
   [0.]]

  [[0.]
   [0.]
   [0.]
   ...
   [0.]
   [0.]
   [0.]]]


 [[[0.]
   [0.]
   [0.]
   ...
   [0.]
   [0.]
   [0.]]

  [[0.]
   [0.]
   [0.]
   ...
   [0.]
   [0.]
   [0.]]

  [[0.]
   [0.]
   [0.]
   ...
   [0.]
   [0.]
   [0.]]

  ...

  [[0.]
   [0.]
   [0.]
   ...
   [0.]
   [0.]
   [0.]]

  [[0.]
   [0.]
   [0.]
   ...
   [0.]
   [0.]
   [0.]]

  [[0.

In [71]:
#Here when we load x_train and x_test, will contain the images
#and y_train and y_test will contain the digits that those images represent

In [72]:
print(y_train)
print(y_test)

[5 0 4 ... 5 6 8]
[7 2 1 ... 4 5 6]


In [73]:
model = Sequential()
# the model has two main aspects, the feature extraction (convolution + pooling layer)
# and they classify a fully connected layers that will make a prediction 


In [75]:
# adding a convolutional layer
# here we are specifying 32 fill this size of 3 by 3
# we are using rectified linear unit activation function in our layer
# moreover input image is the size of 28 by 28 and they are grayscale

model.add(Conv2D(32,(3,3),activation = 'relu', input_shape = (28,28,1)))

In [76]:
# now appling the max pooling layer
# size of maxpooling is 2 by 2 which means it will take the maximum value from the 2 by 2 matix of pixels

model.add(MaxPool2D(2,2))

In [83]:
# adding fully connected layer

model.add(Flatten())

model.add(Dense(100,activation = 'relu'))
# we are adding dense layer of 100 nuerons in our output layer using the relu activation function


* flatten serves as connection between the convolution and dense layers
* arranges the pixel values from 2D images to 1D array
* dense is the layer type we will use for out output layer
* dense is a standard layer type that is used in many cases for neural networks


In [82]:
# adding output layer

model.add(Dense(10,activation = 'softmax'))

* here we are adding another dense layer of 10 neurons in our output layer bcz we know that there are only 10 digits (0-9)
* activation function is softmax.
* softmax makes the output sum upto 1 so the output may be interpreted as probabilities
* the model will then make its prediction based on the option that has highest probability

In [85]:
# compiling the model
model.compile(loss= 'sparse_categorical_crossentropy',optimizer = 'adam',metrics = ['accuracy'])


* So once our network is ready, we need to compile it in the same way as we did in our previous activity.

* The only difference we have here is that we are using sparse, categorical cross entropy loss function instead of binary cross entropy loss function because this is a categorical problem, while the previous coding exercise was a binary classification problem.

In [86]:
# fitting the model
model.fit(x_train,y_train,epochs = 10)

Epoch 1/10
1875/1875 [==============================] - 96s 49ms/step - loss: 4.6208 - accuracy: 0.1043
Epoch 2/10
1875/1875 [==============================] - 89s 47ms/step - loss: 4.6051 - accuracy: 0.0987
Epoch 3/10
1875/1875 [==============================] - 89s 47ms/step - loss: 4.6051 - accuracy: 0.0987
Epoch 4/10
1875/1875 [==============================] - 89s 47ms/step - loss: 4.6051 - accuracy: 0.0987
Epoch 5/10
1875/1875 [==============================] - 89s 48ms/step - loss: 4.6051 - accuracy: 0.0987
Epoch 6/10
1875/1875 [==============================] - 89s 48ms/step - loss: 4.6051 - accuracy: 0.0987
Epoch 7/10
1875/1875 [==============================] - 89s 47ms/step - loss: 4.6051 - accuracy: 0.0987
Epoch 8/10
1875/1875 [==============================] - 89s 47ms/step - loss: 4.6051 - accuracy: 0.0987
Epoch 9/10
1875/1875 [==============================] - 89s 47ms/step - loss: 4.6051 - accuracy: 0.0987
Epoch 10/10
1875/1875 [==============================] - 90s 48m

* So to fit our dataset in our model, we are using the fit method. Moreover, we are specifying epochs as a 10, which means that our model will go through our dataset ten times.

In [87]:
# evaluating the model
model.evaluate(x_test,y_test)

313/313 [==============================] - 5s 15ms/step - loss: 4.6052 - accuracy: 0.0980


[4.60518217086792, 0.09799999743700027]